name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read # Mantenha 'read'
  pages: write   # ESSENCIAL
  id-token: write # ESSENCIAL

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20' # Use uma versão LTS estável
      
      # 💡 Adicione as etapas de instalação e build
      - name: Install Dependencies
        run: npm ci # 'ci' é preferível a 'install' em pipelines de build

      - name: Build Project
  run: npm run build # Garanta que este script existe e funciona localmente.
      
  # O restante do seu workflow de deploy (ex: peaceiris/actions-gh-pages)
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
